# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `fron-end` directory
    directory: "/front-end"
    # Target only the staging branch
    target-branch: "hieuso-test"
    # Check the npm registry for updates daily (more responsive to pushes)
    schedule:
      interval: "daily"

  # Enable version updates for Python dependencies
  - package-ecosystem: "pip"
    # Look for a `requirements.txt` in the `root` directory
    directory: "/"
    # Target only the staging branch
    target-branch: "hieuso-test"
    # Check for updates daily (more responsive to pushes)
    schedule:
      interval: "daily"
