name: Broken Link Checker
on:
  push:
    paths:
      - front-end/**
      - .github/**

jobs:
  broken-link-checker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'front-end'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: front-end/package-lock.json

      - name: install dependencies
        run: npm ci

      - name: build project
        run: npm run build

      - name: start server
        run: |
          echo "Starting preview server"
          npx serve -s dist -l 4173 &
          sleep 5
          echo "Server started"

      - name: check server status
        run: |
          echo "Checking server status"
          curl -I http://localhost:4173

      - name: run link checker
        run: |
          echo "Running link checker"
          npx linkinator http://localhost:4173 --config linkinator-config.json

      - name: check server logs
        run: |
          echo "Server logs"
          ps aux | grep 'serve'