name: Deploy to cloud.gov dev space

on:
  push:
    branches:
      - dev
    paths-ignore:
      - front-end/**

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: dev
    secrets: inherit
